### ISSUE TITLE
Todo: Look into adding support for Brax for RL envs

### ISSUE THREAD

**Issue by lebrice** [lebrice/Sequoia#228]
Todo: Look into adding support for Google's cool-looking [Brax framework](https://github.com/google/brax) to get massively parallelized [mujoco-like environments](https://github.com/google/brax/blob/main/brax/envs/halfcheetah.py) with low overhead. (and no closed-source code! :smile: )

- [X] Check if Brax has a gym-compatible API [Yes, it does!](
https://github.com/google/brax/issues/14)
- [ ] Test it out standalone, check for conflicting packages
- [ ] Look into conversions between pytorch and Jax tensors.. Maybe we could get the environment's observations directly on the GPU!
- [ ] ... More to come

**Comment by erikfrey** [comment]
You may find this issue interesting in which we discuss converting between pytorch and jax: https://github.com/google/brax/issues/2
